// import lru from "./ds/LRUCache/index.js";
// import quickSort from "./ds/quickSort/index.js";
// import crypto from "./js-ps/crypto/index.js";
// import TaskRunner from "./js-ps/TaskRunner/index.js";
// import memoizeFunction from "./js-ps/memoizeFunction/index.js";
// import mergeInterval from "./ds/mergeIntervals/index.js";
// import insertInterval from "./ds/insertInterval/index.js";
// import ExpiryCache from "./ds/ExpiryCache/index.js";
// import TimeBasedKeyStore from "./ds/TimeBasedKeyStore/index.js";
// import binarySearch from "./ds/binarySearch/index.js";
// import uberCarParkingInterval from "./ds/uberCarParkingInterval/index.js";
// import nonOverlappingIntervals from "./ds/nonOverlappingIntervals/index.js";
// import meetingRoom1 from "./ds/meetingRoom1/index.js";
// import meetingRooms2 from "./ds/meetingRooms2/index.js";
// import taskScheduler from "./ds/taskScheduler/index.js";
// import maxItemWithGivenSum from "./ds/maxItemWithGivenSum/index.js";
// import kthLargestElements from "./ds/kthLargestElements/index.js";
// import kthClosestElements from "./ds/kthClosestElements/index.js";
// import medianOfStream from "./ds/medianOfStream/index.js";
// import LinkedList from "./ds/linkedList/index.js";
// import linkedListIntersection from "./ds/linkedListIntersection2/index.js";
// import PriorityQueue from "./ds/PriorityQueue/index.js";
import PriorityExpiryCache from "./ds/PriorityExpiryCache/index.js";
// import MaxPriorityQueue from "./ds/MaxPrioityQueue/index.js";
// import coinChange from "./ds/coinChange/index.js";
// import activitySelection from "./ds/activitySelection/index.js";
// import fractionalKnapsack from "./ds/fractionalKnapsack/index.js";
// import jobSequencing from "./ds/jobSequencing/index.js";
// import largestNum from "./ds/largestNum/index.js";
// import permutationBacktracking from "./ds/permutationBacktracking/index.js";
// import ratInMaze from "./ds/ratInMaze/index.js";
// import functionComposition from "./js-ps/functionComposition/index.js";
// import FunctionCalledOnce from "./js-ps/FunctionCalledOnce/index.js";
// import sleep from "./js-ps/sleep/index.js";
// import curry from "./js-ps/curry/index.js";
// import PromiseTimeoutLimit from "./js-ps/PromiseTimeoutLimit/index.js";
// import promisePool from "./js-ps/promisePool/index.js";
// import flattenNestedArray from "./js-ps/flattenNestedArray/index.js";
// import ArrayLast from "./js-ps/ArrayLast/index.js";
// import debounce from "./js-ps/debounce/index.js";
// import throttle from "./js-ps/throttle/index.js";
// import jsonStringify from "./js-ps/jsonStringify/index.js";
// import eventEmitter from "./js-ps/eventEmitter/index.js";
// import ArrayWrapper from "./js-ps/ArrayWrapper/index.js";
// import flattenObject from "./js-ps/flattenObject/index.js";
// import advancedCurry from "./js-ps/advancedCurry/index.js";
// import FreqTable from "./ds/FreqTable/index.js";

// import DoublyLinkedList from "./ds/DoublyLinkedList/index.js";
// import minimumPathSum from "./ds/minimumPathSum/index.js";

// import LFUCache from "./ds/LFUCache";

// import sequentialDigits from "./ds/sequentialDigits/index.js";

// import Trie from "./ds/trie/index.js";

// import wordSearch from "./ds/wordSearch/index.js";
// import wordSearch2 from "./ds/wordSearch2/index.js";

// import combinationSum1 from "./ds/combinationSum1/index.js";

// import CombinationSum2 from "./ds/CombinationSum2/index.js";

// import LCS from "./ds/LCS/index.js";

// import NQueens from "./ds/NQueens/index.js";

// import pollyfill from "./js-ps/pollyfill/index.js";

// lru();
// quickSort();
// memoizeFunction();
// crypto();
// TaskRunner();
// mergeInterval();
// insertInterval();
// ExpiryCache();
// TimeBasedKeyStore();
// binarySearch();
// uberCarParkingInterval();
// nonOverlappingIntervals();
// meetingRoom1();
// meetingRooms2();
// taskScheduler();
// maxItemWithGivenSum();
// kthLargestElements();
// kthClosestElements();
// medianOfStream();
// LinkedList();
// linkedListIntersection();
// PriorityQueue();
PriorityExpiryCache();
// MaxPriorityQueue();
// PriorityExpiryCache();
// coinChange();
// activitySelection();
// fractionalKnapsack();
// jobSequencing();
// largestNum();
// permutationBacktracking();
// ratInMaze();
// NQueens();
// functionComposition();
// FunctionCalledOnce();
// sleep();
// curry();
// PromiseTimeoutLimit();
// promisePool();
// flattenNestedArray();
// ArrayLast();
// debounce();
// throttle();
// jsonStringify();
// eventEmitter();
// ArrayWrapper();
// flattenObject();
// advancedCurry();
// pollyfill();
// LCS();
// FreqTable();
// CombinationSum2();
// combinationSum1();
// wordSearch();
// wordSearch2();
// Trie();
// sequentialDigits();
// LFUCache();
// DoublyLinkedList();
// minimumPathSum();
